# Available placeholders: {name}, {tag}, {health}, {maxhealth}.
bossbar-text: "{name}"

# Available colors: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE.
color: "RED"

# Time after which the boss bar will disappear. In seconds.
bossbar-remove-time: 5
